### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by YusufAkyol** [metalshan/Smartjax#1]
Hi,
I congratulate you about this plugin also thanks for sharing with us, developers. It's very very usefull.
I suggest that this plugin may help for "ajax history" if you add some other futures. Or you may also create a new onejust for this purpose. You're very near to this result.
It's just a idea.

Best regards.

**Comment by metalshan** [comment]
Hi Yusuf,

Thanks for writing. I didn't get the term "ajax history". Smartjax is already caching the responses. What do you exactly mean by "ajax history"? And where it can be useful?

Thanks,
      Paul

**Comment by YusufAkyol** [comment]
Hi,

May be I had to say "browser history":  http://diveintohtml5.info/history.html
Your plugin is very different approach and easy use for ajax req/resp.
Meanwhile, you may carete a plugin like
https://github.com/arvgta/ajaxify/ ,
https://github.com/browserstate/history.js ,
http://benalman.com/code/projects/jquery-bbq/docs/files/jquery-ba-bbq-js.html , 
http://navi.grantcr.com/#!/home , https://github.com/defunkt/jquery-pjax ,
http://www.minddust.com/project/jquery-pjaxr/ ,
https://github.com/salvan13/jquery-pusher etc.

Best regards.

On Sun, Mar 15, 2015 at 7:34 PM, Paul Shan notifications@github.com wrote:

> Hi Yusuf,
> 
> Thanks for writing. I didn't get the term "ajax history". Smartjax is
> already caching the responses. What do you exactly mean by "ajax history"?
> And where it can be useful?
> 
> Thanks,
> Paul
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/metalshan/Smartjax/issues/1#issuecomment-81174056.

## 

Her şey gönlünüzce olsun...
Selam ve sevgilerimle...

Yusuf Akyol

**Comment by metalshan** [comment]
Thanks Yusuf for the suggestion. Smartjax can be more useful with the support of browser history.
The only problem is, the size of browser storage. The way Smartjax is working now, it won't be efficient to save browsing history. Some approach changes must be done.
Will work into this.
