### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by IsaacHub** [metalshan/Smartjax#11]
Chrome and all browsers throw the following error.
Uncaught ReferenceError: module is not defined at smartjax.min.js:1:5881

What could be the cause?

**Comment by metalshan** [comment]
have done some changes and released `2.1.2`. Can you check now with the new code?

**Comment by IsaacHub** [comment]
@metalshan Thanks for the update. New version is working.
