### ISSUE TITLE
ajax request queue support

### ISSUE THREAD

**Issue by murliatdure** [metalshan/Smartjax#2]
Hello,
Thanks for the smart way of handilng the ajax requests..

Do we have some "Queue Management" - say 
- In case of network unavailability - enqueue the requeue for handling the offline support
- In case of error, we can maintain the failures bucket

would be great to have some queues/buckets for the same.

**Comment by metalshan** [comment]
If a particular call is saved in Smartjax store, it will return you the response even if you are disconnected. But there's no queue support for the first call and I think it will not be very useful also, as the one who is making the call will not be interested to get a response after a very long time. (Kindly correct me if I am wrong)

Smartjax will have history api support in near future, which will help you to browse a site in offline (once loaded)
