### ISSUE TITLE
Time based expiration

### ISSUE THREAD

**Issue by surgevelocityllc** [metalshan/Smartjax#4]
If you can add a feature for time based expiration, you have a winner!

Ex: {expire: 300} passed in to Smartjax so for the next 5 minutes, regardless of tab or page change, the call will hit cache.

**Comment by IsaacHub** [comment]
@metalshan Could you please add the suggested feature requested by @surgevelocityllc ?

**Comment by metalshan** [comment]
@IsaacHub Is it an urgent requirement?

**Comment by mircobabini** [comment]
it would be useful for me as well

**Comment by metalshan** [comment]
Will provide feature by Feb 1st :)

**Comment by metalshan** [comment]
Requested feature is given.
You can auto clear data after a certain time-window. Can also set exceptions in some calls. Group clear and clearing everything basing on the oldest call is also possible.
https://github.com/VoidCanvas/Smartjax/releases/tag/2.2.0

Currently available on github. npm will be updated on next Tuesday.

**Comment by metalshan** [comment]
Published to npm. Closing the issue.
