### ISSUE TITLE
Only when trying to cache, throws: Unexpected token u

### ISSUE THREAD

**Issue by jsh562** [metalshan/Smartjax#7]
Hello,

I replaced my jquery ajax with smartajax and it runs fine when its not caching but when it tries to cache, it returns "unexpected token u" where "u" is from "undefined".

Using these settings:

```
store: "tab"
id
group
force:false
```

I tried different permutations of using `id` and/or `group` to see if its related, no difference in behavior other than expected.
`Store: "page"` and it works fine on refresh, as expected.
`Force: true` and it works fine every time, as expected.

As soon as I turn `force`to `false` or `store`to `tab`, it gives me this error.

Usually returns json.

**Comment by metalshan** [comment]
can you share me the response of your api?

**Comment by jsh562** [comment]
"undefined"?

**Comment by metalshan** [comment]
You can send an empty object rather than undefined to resolve this issue; as smartjax assumes the response to be a json.
Else you can make some changes in https://github.com/VoidCanvas/Smartjax/blob/master/dev_modules/store-service.js, may be a try catch to handle the json parse

**Comment by jsh562** [comment]
Sorry, I might not have been clear.
It is throwing the error because the response is "undefined".
It usually responds with json, and json is what it is trying to respond with when cached, but it returns "undefined".

**Comment by metalshan** [comment]
Didn't get you. Is it like...
1. Your rest api is responding with a valid JSON and after caching when you are making the call again, Smartjax is making that valid JSON undefined?
or
2. Whenever your rest api returns nothing (or undefined), than all the problem occurs?

**Comment by jsh562** [comment]
1. 

My scripts work fine as is when I do not implement smartjax and it returns valid JSON. 

When I change my ajax calls to smartjax and turn on caching, it turns my valid JSON to "undefined". 

When I change my ajax calls to smartjax but turn off caching, it returns valid JSON.

**Comment by metalshan** [comment]
mmm... it shouldn't be though. Can u share some piece of code or something, so that I can debug or something?

**Comment by metalshan** [comment]
As we haven't hear from @jsh562 anymore; so closing the issue.
